defaults:
  - /reward: pixelwise_accuracy

actor_save_path: null #./loop2.0/actor3.ckpt #./divergence_loop/actor2_3.ckpt #./CGPT_Loop/actor_v4.ckpt
critic_save_path: null #./loop2.0/critic3.ckpt #./divergence_loop/critic2_3.ckpt #./CGPT_Loop/critic_v4.ckpt

predict_save_dir: null #./loop2.0/ds
