_target_: datamodules.ES_ED_datamodule.ESEDDataModule

data_dir: '/home/local/USHERBROOKE/juda2901/dev/data/icardio/ES_ED_train_subset_affine/'
csv_file: 'subset_official_test.csv'

subset_frac: 1.0
test_frac: 0.1
available_gt: 0.0
approx_gt_dir: ${logger.save_dir}
splits_column: split_0
