_target_: SectorDataModule.SectorDataModule

data_path: '/home/local/USHERBROOKE/juda2901/dev/data/icardio/train_subset/'
csv_file: '/home/local/USHERBROOKE/juda2901/dev/data/icardio/train_subset/subset.csv'

subset_frac: 0.1
test_frac: 0.1
