_target_: SectorDataModule.SectorDataModule

data_dir: '/home/local/USHERBROOKE/juda2901/dev/data/icardio/train_subset_10k/'
csv_file: 'subset_w_split_0_pred.csv'

subset_frac: 1.0
test_frac: 0.1
approx_gt_dir: ${logger.save_dir}
available_gt: 0.0
