_target_: SectorDataModule.SectorDataModule

data_path: '/home/local/USHERBROOKE/juda2901/dev/data/icardio/train_subset_1k/'
csv_file: '/home/local/USHERBROOKE/juda2901/dev/data/icardio/train_subset_1k/subset.csv'

subset_frac: 1.0
test_frac: 0.1
available_gt: 0.0
