work_dir: ${hydra:runtime.cwd}/

#runner: supervised_runner
#
#global_overrides:
#  "trainer.max_epochs": 250
#  work_dir: ${hydra:runtime.cwd}/
#  seed: 2
#  run_name: data_qty_test
#
#exp_overrides:
#  "datamodule.subset_frac": [0.003, 0.01, 0.05, 0.1, 0.25, 0.5, 1]



runner: RL_runner

global_overrides:
  "trainer.max_epochs": 10
  work_dir: ${hydra:runtime.cwd}/
  seed: 2
  run_name: use_gt_exp

exp_overrides:
  "datamodule.available_gt": [0.0] #, 0.01, 0.05, 0.1, 0.25, 0.5, 1]