work_dir: ${hydra:runtime.cwd}
run_name: test

defaults:
  - logger: tensorboard
  - model: rewardnet
  - datamodule: rewardnet_diff
  - callbacks: default

  - _self_

datamodule:
  data_path: ./loop2.0/ds/

model:
  save_model_path: ./loop2.0/reward_net2.ckpt

seed: 1

logger:
  name: '${get_class_name: ${model._target_}}_${run_name}'

callbacks:
  model_checkpoint:
    monitor: val_loss
    mode: min

run_predict: False

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 100
  log_every_n_steps: 1
  gpus: 1
  #num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
