work_dir: ${hydra:runtime.cwd}
run_name: default

defaults:
  - _self_
  - logger: tensorboard
  - model: ppo
  - datamodule: sector
  - callbacks: default

seed: 1

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 5
  log_every_n_steps: 1
  gpus: 1
#  num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
