work_dir: ${hydra:runtime.cwd}
run_name: default

defaults:
  - logger: tensorboard
  - model: ppo
  - datamodule: sector
  - callbacks: default
  - _self_

seed: 1

datamodule:
  gt_column: Gt_0
#  gt_frac: 1.0

predict_subset_frac: 0.1

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 15
  log_every_n_steps: 1
  gpus: 1
#  num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
