work_dir: ${hydra:runtime.cwd}

defaults:
  - _self_
  - logger: tensorboard
  - model: pg
  - datamodule: sector
  - callbacks: default

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  log_every_n_steps: 1
  gpus: 1
