work_dir: ${hydra:runtime.cwd}

defaults:
  - _self_
  - logger: tensorboard
  - model: ppo
  - datamodule: sector
  - callbacks: default

seed: 0

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  log_every_n_steps: 1
  gpus: 1
