work_dir: ${hydra:runtime.cwd}
run_name: supervised_default

defaults:
  - logger: tensorboard
  - model: supervised
  - datamodule: ???
  - callbacks: default
  - _self_
  - experiment: supervised_camus

seed: 1

logger:
  name: '${get_class_name: ${model._target_}}_${run_name}'

callbacks:
  model_checkpoint:
    monitor: val_acc

predict_subset_frac: 1000

ckpt_path: null

datamodule:
  gt_column: Gt_0

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 50
  log_every_n_steps: 1
  gpus: 1
  #num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)

# Prefer old Hydra default of changing directory for each job from version<=1.1
hydra:
  job:
    chdir: True