work_dir: ${hydra:runtime.cwd}/../
run_name: test

defaults:
  - logger: tensorboard
  - model: supervised
  - datamodule: sector
  - callbacks: default

  - _self_

seed: 1

logger:
  name: '${get_class_name: ${model._target_}}_${run_name}'

callbacks:
  model_checkpoint:
    monitor: val_acc

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  log_every_n_steps: 1
  gpus: 1
  num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
