
num_iter: 4
run_name: camus_2rewards
output_path: ${oc.env:LOG_PATH}/${run_name}/

pretrain_path: /data/rl_logs/lm_camus_test/pretrained_norand_moredata.ckpt

var_file: ${output_path}/variables.pkl

target: camus
source: camus

#
# supervised params
#
sup_num_epochs: 3

# Increases randomness in initial model
sup_loss_label_smoothing: 0.0

#
# RL params
#
rl_num_epochs: 5
rl_num_predict: 10000
rl_overrides: []

#
# RewardNet params
#
rn_num_epochs: 50
