work_dir: ${hydra:runtime.cwd}
run_name: default

defaults:
  - logger: tensorboard
  - model: ppo
  - datamodule: ???
  - callbacks: default
  - _self_
  - experiment: ppo_camus

seed: 1

logger:
  save_dir: ./logs/camus_start_es_ed_ppo

ckpt_path: './logs/camus_start_es_ed_ppo/PPO_RewardUnet_es_ed/version_3/checkpoints/epoch=1-step=3880.ckpt' #???

trainer:
  _target_: pytorch_lightning.Trainer
  log_every_n_steps: 1
  gpus: 1
#  num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
