work_dir: ${hydra:runtime.cwd}
run_name: test

logger_run_name: '${get_class_name: ${model._target_}}_${run_name}'

defaults:
  - logger: comet
  - model: image_quality_3d
  - datamodule: image_quality_3d_datamodule
  - callbacks: default

  - _self_

seed: 1

callbacks:
  model_checkpoint:
    monitor: val/loss
    mode: min

run_predict: False

train: True

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: 50
  log_every_n_steps: 1
  accelerator: gpu
  accumulate_grad_batches: 32
  devices: 1
