work_dir: ${hydra:runtime.cwd}
run_name: test

defaults:
  - logger: tensorboard
  - model: rewardnet_3d
  - datamodule: rewardnet_diff_3d
  - callbacks: default

  - _self_

seed: 1

logger:
  name: '${get_class_name: ${model._target_}}_${run_name}'

callbacks:
  model_checkpoint:
    monitor: val_loss
    mode: min

run_predict: False

train: True

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 50
  log_every_n_steps: 1
  gpus: 1
  accumulate_grad_batches: 8
  #num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
