work_dir: ${hydra:runtime.cwd}
run_name: default

defaults:
  - logger: comet
  - model: ppo
  - datamodule: ???
  - callbacks: default
  - _self_
  - experiment: ppo_es_ed

seed: 1

logger:
  experiment_name: '${get_class_name: ${model._target_}}_${get_class_name: ${model.reward._target_}}_${run_name}'

datamodule:
#  subset_frac: 0.1
 gt_column: Gt_0

predict_subset_frac: 1000
train: True

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  log_every_n_steps: 1
  gpus: 1
#  num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
