work_dir: ${hydra:runtime.cwd}
run_name: supervised_default

defaults:
  - logger: tensorboard
  - model: supervised_3d
  - datamodule: cardinal_3d
  - callbacks: default
  - _self_
#  - experiment: supervised_camus

seed: 1

logger:
  name: '${get_class_name: ${model._target_}}_${run_name}'

callbacks:
  model_checkpoint:
    monitor: val_dice

predict_subset_frac: 1000

#datamodule:
#  use_dataset_fraction: 0.1

train: True

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 10
  log_every_n_steps: 1
  gpus: 1
  #num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
