work_dir: ${hydra:runtime.cwd}
run_name: supervised_default

logger_run_name: '${get_class_name: ${model._target_}}_${run_name}'

defaults:
  - logger: comet
  - model: supervised
  - datamodule: ???
  - callbacks: default
  - _self_
  - experiment: supervised_camus

seed: 1

callbacks:
  model_checkpoint:
    monitor: val_dice

predict_subset_frac: 1000

datamodule:
  gt_column: Gt_0

train: True

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 50
  log_every_n_steps: 1
  gpus: 1
  #num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
