work_dir: ${hydra:runtime.cwd}
run_name: ts-it_baseline

defaults:
  - logger: tensorboard
  - model: ts-it
  - datamodule: ???
  - callbacks: default
  - _self_
  - experiment: ts_it

seed: 1

logger:
  save_dir: ${oc.env:LOG_PATH}/test/
  name: '${get_class_name: ${model._target_}}_${model.class_label}'

callbacks:
  model_checkpoint:
    monitor: val_acc


datamodule:
  gt_column: Gt_0

train: True

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: 50
  log_every_n_steps: 1
  accelerator: gpu
  #num_sanity_val_steps: 0 # skip sanity check (convenient for debugging directly in train step)
