defaults:
  - /model/net@net: unet

_target_: rl4echo.reward.classic_reward.RewardUnet3D

#state_dict_path: reward_net_3d_landmarks2-0.ckpt #reward_net_3d_landmarks.ckpt
state_dict_path: rewardnet_5000best.ckpt

temp_factor: 1

net:
  in_channels: 2
  num_classes: 1
