# @package _global_

defaults:
  - alliancecan
  - override /hydra/launcher: cedar

hydra:
  launcher:
#    gpus_per_node: 2
    gres: gpu:v100l:2
    tasks_per_node: 2

trainer:
  strategy: ddp_find_unused_parameters_true
  devices: 2
  accumulate_grad_batches: 1

datamodule:
  num_workers: 2