# @package _global_

defaults:
  - alliancecan
  - override /hydra/launcher: cedar

hydra:
  launcher:
    gpus_per_node: 4
    tasks_per_node: 4

trainer:
  strategy: ddp
  devices: 4

datamodule:
  num_workers: 2